name: HMS Application

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.2.2
      - name: Format with Ruff
        run: |
          ruff format .
      - name: Check Diff
        run: |
          git diff --exit-code
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd ./backend
          poetry install --with dev
      - name: Lint with ruff
        run: |
          cd ./backend && poetry run ruff check .
      - name: Mypy static check
        run: |
          cd ./backend && poetry run mypy .
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd ./backend
          poetry install --with dev
      - name: Run Pytest
        run: |
          cd ./backend && poetry run pytest --durations=10 --color=yes -vv
